services:
  - type: web
    name: paperlens-api
    runtime: docker
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    plan: free
    healthCheckPath: /
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: LANGGRAPH_STRICT_MSGPACK
        value: "true"

  - type: web
    name: paperlens-frontend
    runtime: docker
    dockerfilePath: ./app/Dockerfile
    dockerContext: ./app
    plan: free
    envVars:
      - key: API_URL
        sync: false